services:
  postgres:
    image: postgres:17-alpine
    container_name: scalable-test-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scalable_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  sqs:
    image: localstack/localstack:latest
    container_name: localstack-sqs
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./infrastructure/localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"

  service:
    container_name: scalable-service
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - sqs